config/routes.rb
R20130212MountainsOceans::Application.routes.draw do
  get '/mountains' => 'mountains#index'
  get '/mountains/new' => 'mountains#new'
  post '/mountains' =>  'mountains#create'
  get '/mountains/:id' => 'mountains#show', :as => 'mountain'
  post '/mountains/:id/delete' => 'mountains#destroy', :as => 'mountain_delete'
  get '/mountains/:id/edit' => 'mountains#edit', :as => 'mountain_edit'
  post '/mountains/:id' => 'mountains#update'

  root :to => 'mountains#index'
end

app/models/mountain.rb
# == Schema Information
#
# Table name: mountains
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  height     :integer
#  image      :string(255)
#  continent  :string(255)
#  range      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Mountain < ActiveRecord::Base
  attr_accessible :name, :height, :image, :continent, :range
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mountains_controller.rb
class MountainsController < ApplicationController
  def index
    @mountains = Mountain.all
  end

  def new
  end

  def create
    Mountain.create(params[:mountain])
    redirect_to(mountains_path)
  end

  def show
    @mountain = Mountain.find(params[:id])
  end

  def destroy
    mountain = Mountain.find(params[:id])
    mountain.delete
    redirect_to(mountains_path)
  end

  def edit
    @mountain = Mountain.find(params[:id])
  end

  def update
    mountain = Mountain.find(params[:id])
    mountain.update_attributes(params[:mountain])
    redirect_to(mountains_path)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>R20130212MountainsOceans</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
  <nav>
    <ul>
      <li><%= link_to("All", mountains_path ) %></li>
      <li> <%= link_to("New", mountains_new_path) %> </li>
    </ul>
  </nav>

<body>

<%= yield %>

</body>
</html>

app/views/mountains/edit.html.erb
<form method="post" action='<%= mountain_path(@mountain.id) %> '>
  Name: <input type="text" name="mountain[name]" value='<%= @mountain.name %> 'autofocus>
  <br>
  Height: <input type="text" name="mountain[height]" value='<%= @mountain.height %>'  >
  <br>
  Image: <input type="text" name="mountain[image]" value='<%= @mountain.image %>'>
  <br>
  Continent: <input type="text" name="mountain[continent]" value='<%= @mountain.continent %>'>
  <br>
  Range: <input type="text" name="mountain[range]" value='<%= @mountain.range %>'>
   <br>
    <button>Edit</button>
</form>

app/views/mountains/index.html.erb
List of mountains
<br>
<br>

<% @mountains.each do |mountain| %>
  <br>
  Name: <%= link_to( mountain.name, mountain_path(mountain.id)) %>
  <br>
  Height: <%= number_with_delimiter(mountain.height) %>
  <br>
  <%= link_to("edit", mountain_edit_path(mountain.id)) %>
  <br>
  <%= button_to "Delete", mountain_delete_path(mountain.id) %>

<% end %>

app/views/mountains/new.html.erb
<form method="post" action="/mountains">
  Name: <input type="text" name="mountain[name]" autofocus>
  <br>
  Height: <input type="text" name="mountain[height]">
  <br>
  Image: <input type="text" name="mountain[image]">
  <br>
  Continent: <input type="text" name="mountain[continent]">
  <br>
  Range: <input type="text" name="mountain[range]">
   <br>
    <button>Add</button>
</form>

app/views/mountains/show.html.erb
Name: <%= @mountain.name %>
<br>
Height: <%= @mountain.height %>
<br>
Continent: <%= @mountain.continent %>
<br>
Range: <%= @mountain.range %>
<br>
Image:
<%= image_tag(@mountain.image) %>